myStr = "Gilbert"

print("My name is " + myStr)
print("My name is {0}".format(myStr))
# se puede utilizar desde la version 3.6 en adelante
print(f"My name is {myStr}")

# print(dir(myStr))

# print(myStr.upper())
# print(myStr.lower())
# print(myStr.swapcase())
# print(myStr.capitalize())
# print(myStr.replace('hello', 'bye'))
# print(myStr.count(' '))
# print(myStr.startswith('H'))
# print(myStr.endswith('d'))
# print(myStr.split())
# print(myStr.find('o'))
# print(len(myStr))
# print(myStr.index('e'))
# print(myStr.isnumeric())
# print(myStr.isalpha())
# print(myStr[0])
# print(myStr[1])
# print(myStr[2])
# print(myStr[3])
# print(myStr[4])
# print(myStr[-5])
# print(myStr[-4])
# print(myStr[-2])
# print(myStr[-1])
